### ISSUE TITLE
TypeError: Cannot read property 'database' of undefined

### ISSUE THREAD

**Issue by petemyron** [node-influx/node-influx#134]
I've tried both methods to configure a client:

```js
var client = influx(
  {
    host: 'http://influx.whatever',
    port: 8086,
    protocol: 'http',
    username: 'root',
    password: 'root',
    database: 'whatever'
  }
)
```
and
```js
var client = influx('http://root:root@influx.whatever:8086/whatever')
```

and in both cases, calling `client.writePoint("test", { value: 123, value2: 456 })` results in an error regarding the database property with something like: 
```
  if (!options.database) {
              ^

TypeError: Cannot read property 'database' of undefined
    at InfluxDB.writeSeries (/Users/pmyron/node_modules/influx/index.js:311:15)
    at InfluxDB.writePoint (/Users/pmyron/node_modules/influx/index.js:333:8)
    at Object.<anonymous> (/Users/pmyron/workspace/influx-nodejs/influx.js:17:8)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

When I inspect the client object, I can see that it's there in the first case:
```
{ options:
   { hosts: [],
     disabled_hosts: [],
     username: 'root',
     password: 'root',
     port: 8086,
     protocol: 'http',
     depreciatedLogging: [Function: bound ],
     failoverTimeout: 60000,
     requestTimeout: null,
     maxRetries: 2,
     timePrecision: 'ms',
     host: 'http://influx.whatever',
     database: 'whatever' },
  request:
   InfluxRequest {
     index: 0,
     hostsAvailable: [ [Object] ],
     hostsDisabled: [],
     defaultRequestOptions: { timeout: null },
     options: { failoverTimeout: 60000, maxRetries: 2 } } }
```
, but not in the second via url:
```
{ options:
   { '0': 'h',
     '1': 't',
     '2': 't',
     '3': 'p',
     '4': ':',
     '5': '/',
     '6': '/',
     '7': 'r',
     '8': 'o',
     [...snip],
     hosts: [],
     disabled_hosts: [],
     username: 'root',
     password: 'root',
     port: 8086,
     protocol: 'http',
     depreciatedLogging: [Function: bound ],
     failoverTimeout: 60000,
     requestTimeout: null,
     maxRetries: 2,
     timePrecision: 'ms' },
  request:
   InfluxRequest {
     index: 0,
     hostsAvailable: [],
     hostsDisabled: [],
     defaultRequestOptions: { timeout: null },
     options: { failoverTimeout: 60000, maxRetries: 2 } } }
```

I assume it's related. What's going on?

```
npm list influx
/Users/pmyron
└── influx@4.1.0
```

**Comment by bencevans** [comment]
Hi, using a url to instantiate the client isn't yet supported in any released version. It's only just been added to the project. If you wish to use it you can install the influx module from the git repository.

This is an odd error. If you could try this pull-request https://github.com/node-influx/node-influx/pull/135 and let me know if it fixes the problem for you, we'll get it shipped soon.

I believe it's because the options parameter isn't being provided to `writePoint()`.

**Comment by jmny** [comment]
> 

you're right 

```
// ok
client.writePoints('serie1', [[{value1:1, value2:4}, {tag1:'plop'}]], {});
// ko
client.writePoints('serie1', [[{value1:1, value2:4}, {tag1:'plop'}]]);

```

**Comment by connor4312** [comment]
Sounds like this issue is now resolved, please let us know if that's not the case!
