### ISSUE TITLE
Continue to see `404 page not found` when running simple query

### ISSUE THREAD

**Issue by shaunwarman** [node-influx/node-influx#158]
Influx version: 0.8.8
node-influx version: @3.5.0
node version: 6.0.0

Request:
```
const Config = require('./config');
const Influx = require('influx');

const { database, host, port, protocol, username } = Config.influxDB;

const client = Influx({
    host,
    port,
    protocol,
    username,
    password: process.env.INFLUX_PASSWORD,
    database
});

const query = 'select * from request where time > now() - 100m and status >= 400';

client.query(query, (error, results) => {
    if (error) {
        console.log(error);
        return;
    }
    console.log(results);
});
```

Response:
```
Error: 404 page not found

    at /Users/swarman/Development/Source/nodeops-influx/node_modules/influx/index.js:54:23
    at InfluxRequest._parseCallback (/Users/swarman/Development/Source/nodeops-influx/node_modules/influx/lib/InfluxRequest.js:130:10)
    at Request._callback (/Users/swarman/Development/Source/nodeops-influx/node_modules/influx/lib/InfluxRequest.js:118:10)
    at Request.self.callback (/Users/swarman/Development/Source/nodeops-influx/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/swarman/Development/Source/nodeops-influx/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/swarman/Development/Source/nodeops-influx/node_modules/request/request.js:965:12)
```

**Comment by shaunwarman** [comment]
Port was off

![](http://media1.giphy.com/media/NZhO1SEuFmhj2/giphy.gif)

**Comment by connor4312** [comment]
Oop! Let us know if you have other issues 😄
