### ISSUE TITLE
Error when connecting over HTTPS: unable to verify the first certificate

### ISSUE THREAD

**Issue by dandv** [node-influx/node-influx#176]
Has anyone tried using the library over HTTPS? I'm connecting like this,

```js
const influx = require('influx')({
  host: 'dandascalescu.com',
  protocol: 'https',
  [...]
});
```

But get this error:

```
Error: Error: unable to verify the first certificate
    at /code/influx/index.es6:87:20
    at /code/influx/node_modules/influx/index.js:99:14
    at InfluxRequest._parseCallback (/code/influx/node_modules/influx/lib/InfluxRequest.js:122:10)
    at Request._callback (/code/influx/node_modules/influx/lib/InfluxRequest.js:111:10)
    at self.callback (/code/influx/node_modules/request/request.js:198:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/code/influx/node_modules/request/request.js:867:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
```

**Comment by dandv** [comment]
Fixed by documenting upstream how to properly integrate with LetsEncrypt certificates.

**Comment by NomikOS** [comment]
The option 
`  protocol: 'https',`
solved my issue
