### ISSUE TITLE
"Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by Harrison-M** [node-influx/node-influx#228]
As of 5.0.0-alpha.1, specifying `https` as the protocol for a single-host configuration produces the following error:

```
Error: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:55:11)
    at Object.exports.request (http.js:31:10)
    at Pool.stream (/Users/harrison/Projects/binscrap/node_modules/influx/lib/src/pool.js:215:26)
    at Promise (/Users/harrison/Projects/binscrap/node_modules/influx/lib/src/pool.js:127:18)
    at Pool.text (/Users/harrison/Projects/binscrap/node_modules/influx/lib/src/pool.js:126:16)
    at Pool.json (/Users/harrison/Projects/binscrap/node_modules/influx/lib/src/pool.js:119:21)
    at InfluxDB.queryRaw (/Users/harrison/Projects/binscrap/node_modules/influx/lib/src/index.js:790:26)
    at InfluxDB.query (/Users/harrison/Projects/binscrap/node_modules/influx/lib/src/index.js:773:21)
    at Object.<anonymous> (/Users/harrison/Projects/binscrap/influxtest.js:25:22)
    at Module._compile (module.js:556:32)
```

I have not tested this against a clustered configuration yet.

**Comment by connor4312** [comment]
Thanks for the report! This has been fixed in `5.0.0-alpha.3`
