### ISSUE TITLE
cannot connect to my influxdb cloud instance

### ISSUE THREAD

**Issue by jonathanong** [node-influx/node-influx#248]
as i assume it uses self-signed SSL certificates. i get the following error:

```bash
      Error: write EPROTO 140735755973568:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
      
          at exports._errnoException (util.js:1022:11)
          at WriteWrap.afterWrite (net.js:801:14)
```

how do i get around this? i am using node v6.9.2 and node influx v5.0.3

**Comment by jonathanong** [comment]
nvm. was because i was using `hostname` instead of `host`. would be nice if the options conformed to `require(`url`)` standards
