### ISSUE TITLE
Can't 'getNanoTime' or 'toNanoISOString' when time has no decimals

### ISSUE THREAD

**Issue by gomezjdaniel** [node-influx/node-influx#261]
By having as a result of a query the following:

```
{
  "results": [
    {
      "statement_id": 0,
      "series": [
        {
          "name": "status_message",
          "columns": [
            "time",
            "sum"
          ],
          "values": [
            [
              "2017-02-17T08:00:00Z",
              0
            ],
            [
              "2017-02-17T16:00:00Z",
              1
            ],
            [
              "2017-02-18T00:00:00Z",
              1
            ],
            [
              "2017-02-18T08:00:00Z",
              1
            ],
            [
              "2017-02-18T16:00:00Z",
              1
            ],
            [
              "2017-02-19T00:00:00Z",
              1
            ],
            [
              "2017-02-19T08:00:00Z",
              1
            ],
            [
              "2017-02-19T16:00:00Z",
              1
            ],
            [
              "2017-02-20T00:00:00Z",
              1
            ],
            [
              "2017-02-20T08:00:00Z",
              5
            ]
          ]
        }
      ]
    }
  ]
}
```

When calling getNanoTime or toNanoISOString the following exception is thrown:

```
> TypeError: Cannot read property 'slice' of undefined
    at nanoIsoToTime (/truckparking/http-server/node_modules/influx/lib/src/grammar/times.js:133:38)
    at Date.toNanoISOStringFromISO [as toNanoISOString] (/truckparking/http-server/node_modules/influx/lib/src/grammar/times.js:145:36)
    at result.forEach (/truckparking/http-server/lib/db-wrapper/mongo-influx/index.js:184:39)
    at Array.forEach (native)
    at influx.query.then.result (/truckparking/http-server/lib/db-wrapper/mongo-influx/index.js:183:18)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

Which comes from here https://github.com/node-influx/node-influx/blob/cc02c4d46a49f8b626063388a2b54f58ae868541/src/grammar/times.ts#L186 as decimal part is not represented in the output of the influx query

**Comment by connor4312** [comment]
Hi, thanks for the report! I've fixed this and published it in version 5.0.5.
