### ISSUE TITLE
Can not alter retention policy

### ISSUE THREAD

**Issue by Princha** [node-influx/node-influx#304]
I'm using ubuntu16.04 with InfluxDB 0.10.0 and Nodejs v8.4.0, but it can not alter retention policy when I using alterRetentionPolicy method, even the createRetentionPolicy and dropRetentionPolicy method are invalid.
This is the return:
```
null: Error: A 405 Method Not Allowed error occurred: Method Not Allowed
message: "A 405 Method Not Allowed error occurred: Method Not Allowed
"
req: ClientRequest {domain: null, _events: Object, _eventsCount: 3, …}
res: IncomingMessage {_readableState: ReadableState, readable: false, domain: null, …}
stack: "Error: A 405 Method Not Allowed error occurred: Method Not Allowed

    at new RequestError (/usr/local/lib/node_modules/influx/lib/src/pool.js:52:28)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/influx/lib/src/pool.js:62:53)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)"
__proto__: Error {constructor: }
```

**Comment by mahnuh** [comment]
I have the same issue, did you find a solution @Princha ?
