### ISSUE TITLE
Randomly getting UnhandledPromiseRejectionWarning in influxDB.writePoints

### ISSUE THREAD

**Issue by amitmaniar** [node-influx/node-influx#341]
(node:6771) UnhandledPromiseRejectionWarning: Error: A 400 Bad Request
    at new RequestError (/root/node_modules/influx/lib/src/pool.js:52:
    at IncomingMessage.<anonymous> (/root/node_modules/influx/lib/src/
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

is this similar to #250 ?
After this application just exits.

**Comment by konstantinblaesi** [comment]
Listen on https://nodejs.org/api/process.html#process_event_unhandledrejection

**Comment by amitmaniar** [comment]
I think the bug is within node-influx.

**Comment by konstantinblaesi** [comment]
@amitmaniar I think you're right, I am able to reproduce this with a very similar stack trace
```
(node:10331) UnhandledPromiseRejectionWarning: Error: A 400 Bad Request error occurred: {"error":"unable to parse 'inverters': missing fields"}

    at new RequestError (/some/project/node_modules/influx/lib/src/pool.js:52:28)
    at IncomingMessage.<anonymous> (/some/project/node_modules/influx/lib/src/pool.js:63:53)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:10331) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10331) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The rejection seems to be coming from https://github.com/node-influx/node-influx/blob/master/src/pool.ts#L257
I don't understand why this rejection is claimed to be unhandled though and my attempts at finding/fixing anything have been unsuccessful. *However* I had a small bug in my usage of writeMeasurement/writePoints
```
await this._influxClient.writeMeasurement(schema.measurement, [
            points ], {
                database: config.database,
                retentionPolicy: schema.retentionPolicy,
                precision: 's'
            });
```
I passed `[ points ]` by accident. After fixing this to just `points` my unhandled rejection was gone.

**Comment by Jinhanzhang** [comment]
Hi, I have the same problem when I use influx.writePoints, so what is the cause of this problem and how should I fix it?
