### ISSUE TITLE
read ECONNRESET

### ISSUE THREAD

**Issue by milu2003** [node-influx/node-influx#471]
In case of large number of inserts, failure

```
for (var i = 0; i < 1000; i++) {
            influx.writePoints([
          {
            measurement: 'response_times',
            tags: { host: os.hostname() },
            fields: { duration: 12, path: req.path },
          }
        ]).catch(err => {
          console.error(`Error saving data to InfluxDB! ${err.stack}`)
        })
    }
```

err: 
```
Error saving data to InfluxDB! Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Error saving data to InfluxDB! Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Error saving data to InfluxDB! Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Error saving data to InfluxDB! Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Error saving data to InfluxDB! Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Error saving data to InfluxDB! Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Error saving data to InfluxDB! Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Error saving data to InfluxDB! Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
```

It's only 1000. Poor performance

**Comment by bencevans** [comment]
I suggest looking at the InfluxDB logs. You may find you get better performance by batch writing rather than writing individual points.

> You might have guessed it already: it's a connection error.
>
> "ECONNRESET" means the other side of the TCP conversation abruptly closed its end of the connection. This is most probably due to one or more application protocol errors. You could look at the API server logs to see if it complains about something.

https://stackoverflow.com/questions/17245881/node-js-econnreset

**Comment by milu2003** [comment]
Later, I changed to batch write to improve the problem.

I always think the performance is too poor. I gave up using it because of this.
