### ISSUE TITLE
Connect to influxDB

### ISSUE THREAD

**Issue by ParkerOu** [node-influx/node-influx#473]
## Expected Behavior
Connect to InfluxDB

## Actual Behavior
Receive error tags property undefined
```js
options.tags.forEach(tag => {
                     ^
TypeError: Cannot read property 'forEach' of undefined
    at new Schema (D:\work\test\influxdb\node_modules\influx\lib\src\schema.js:17:22)
    at InfluxDB._createSchema (D:\work\test\influxdb\node_modules\influx\lib\src\index.js:977:61)
    at InfluxDB._options.schema.forEach.schema (D:\work\test\influxdb\node_modules\influx\lib\src\index.js:239:53)
    at Array.forEach (<anonymous>)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (D:\work\test\influxdb\node_modules\pirates\lib\index.js:104:7)
```
## Steps/Code to Reproduce the Problem

```
import {
    InfluxDB, FieldType,
} from 'influx';

const influx = new InfluxDB({
    host: INFLUX_HOST,
    port: INFLUX_PORT,
    username: INFLUX_USER,
    password: INFLUX_PWD,
    database: INFLUX_DB,
    schema: [
        {
            measurement: 'test_measurement',
            fields: {
                value: FieldType.FLOAT,
                machie: FieldType.STRING,
            },
        },
    ],
    tags: [
        'host',
    ],
});
```

## Specifications

  - Version: Node v10.11.0, Influxdb 1.7.8, node-influx v5.4.2
  - Platform: Windows
  - Subsystem:

**Comment by bencevans** [comment]
Hi! It looks like the `tags` are in the wrong place...

```js
import {
    InfluxDB, FieldType,
} from 'influx';

const influx = new InfluxDB({
    host: INFLUX_HOST,
    port: INFLUX_PORT,
    username: INFLUX_USER,
    password: INFLUX_PWD,
    database: INFLUX_DB,
    schema: [
        {
            measurement: 'test_measurement',
            fields: {
                value: FieldType.FLOAT,
                machie: FieldType.STRING,
            },
            tags: [
                'host',
            ],
        },
    ],
});
```
