### ISSUE TITLE
Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by UltimatumGamer** [node-influx/node-influx#520]
## Expected Behavior
`influx.writeMeasurement({}) ...` Writes sth. in Measurement
## Actual Behavior
```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```
## Steps/Code to Reproduce the Problem
```
const Influx = require('influx');
const influx = new Influx.InfluxDB({
    host: 'localhost',
    database: 'statistic',
    protocol: 'https',
})
influx.writeMeasurement('paste', [{
    fields: {
        type: "SAVE"
    },
}]).catch(err => {
    console.log(err)
})
```

## Specifications

- Version: 5.6.2
- Platform: Windows / Linux

**Comment by bencevans** [comment]
You're able to override the request options by providing an `options` object within your host definition ...

```js
const client = new InfluxDB({
  database: 'my_db',
  username: 'connor',
  password: 'pa$$w0rd',
  hosts: [
    { host: 'db1.example.com', options: { rejectUnauthorized: false} },
    { host: 'db2.example.com' },
  ]
  schema: [{
    measurement: 'perf',
    tags: ['hostname'],
    fields: {
      memory_usage: FieldType.INTEGER,
      cpu_usage: FieldType.FLOAT,
      is_online: FieldType.BOOLEAN,
    }
  }]
})
```

> This code hasn't been run but rather inferred from the docs at https://node-influx.github.io/typedef/index.html#static-typedef-IPoolOptions


Alternatively (not recommended as will disable for everything) providing the environment variable `NODE_TLS_REJECT_UNAUTHORIZED=0` would disable the TLS checking.
