### ISSUE TITLE
ServiceNotAvailableError: No host available with docker and nodejs

### ISSUE THREAD

**Issue by srilakshmikanthanp** [node-influx/node-influx#642]
I encountering this error often, I am using influx inside docker, using `"influx": "^5.9.3"`,

~~~shell
ServiceNotAvailableError: No host available
    at Pool.stream (/usr/src/app/node_modules/influx/lib/src/pool.js:235:29)
    at /usr/src/app/node_modules/influx/lib/src/pool.js:166:18
    at new Promise (<anonymous>)
    at Pool.discard (/usr/src/app/node_modules/influx/lib/src/pool.js:165:16)
    at InfluxDB.writePoints (/usr/src/app/node_modules/influx/lib/src/index.js:854:27)
    at InfluxDBWriter.saveCalculatedOption (/usr/src/app/source/process/writers/influxDBWriter.ts:186:34)
    at InfluxDBWriter.onCalculated (/usr/src/app/source/process/writers/influxDBWriter.ts:226:25)
    at Calculator.notifyListeners (/usr/src/app/source/process/calculator/calculator.ts:18:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
~~~

Compose for influxdb,

~~~yml
services:
  influxdb:
    image: influxdb:1.8.10
    container_name: ${INFLUX_HOSTNAME}
    hostname: ${INFLUX_HOSTNAME}
    ports:
      - "8086:${INFLUX_PORT}"
    volumes:
      - /var/lib/influxdb:/var/lib/influxdb
    restart: always
    networks:
      - ${DOCKER_NETWORK}
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUX_ADMIN_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUX_ADMIN_PASSWORD}
      - INFLUXDB_DB=${INFLUX_HOSTNAME}
      - INFLUXDB_USER=${INFLUX_USERNAME}
      - INFLUXDB_USER_PASSWORD=${INFLUX_PASSWORD}
      - INFLUXDB_DB=${INFLUX_DATABASE}
      - INIT_USERS=true
~~~

How do I fix that ?

System specifications: 

Docker version: Docker version 20.10.16, build aa7e414

~~~shell
Docker stats Snapshot:
~~~

~~~shell
CONTAINER ID   NAME       CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O        PIDS
efbc7d2dd4b9   influxdb   46.14%    295.5MiB / 31.36GiB   0.92%     905MB / 677MB   2.41MB / 639MB   44
~~~

Some piece of code I am using to push,

~~~typescript
private saveCalculatedOption(message: ICalcOptionMessage): Promise<void> {
        return this.influxClient.writePoints([{
            measurement: influxMeasurements.CalcOptionMesurement,
            timestamp: Date.parse(message.date),
            tags: {
                symbol: message.symbol,
                strike: message.strike.toString(),
                option_type: message.option_type,
                lotsize: message.lotsize.toString(),
                expiry: message.expiry
            },
            fields: {
                high: message.high,
                low: message.low,
                open: message.open,
                close: message.close,
                close_diff: message.close_diff,
                val_in_lakh: message.val_in_lakh,
                oi: message.oi,
                oi_diff: message.oi_diff,
                volume: message.volume,
                volume_diff: message.volume_diff,
                cash: message.cash,
                cash_diff: message.cash_diff,
                build_up: message.build_up
            }
        }]);
}
~~~

**Comment by srilakshmikanthanp** [comment]
Thanks for you response,

1) Intermittently
2) Another Container
3) Sure here is,

~~~typescript
import * as property from "../property/property"
import * as Influx from "influx";
import * as models from "../models";

/**
 * Influx db client for app
 */
const influxClient = new Influx.InfluxDB({
    username: property.getInfluxUsername(),
    password: property.getInfluxPassword(),
    database: property.getInfluxDatabase(),
    host: property.getInfluxHost(),
    port: property.getInfluxPort(),
    schema: [
        new models.CalcFutureSchema(),
        new models.CalcOptionSchema(),
        new models.LiveCashSchema(),
        new models.LiveFutureSchema(),
        new models.LiveOptionSchema()
    ]
});

/**
 * Export Influx client
 */
export default influxClient;
~~~

**Comment by bencevans** [comment]
🤔 hmm, I wonder if it's the influx container then, I take it there's nothing of help in the influx container logs? Or is it being restarted as changes are made or something similar? I've got a server running and haven't run into any intermittent connections using the library before.
