### ISSUE TITLE
Database undefined for Writepoint

### ISSUE THREAD

**Issue by kgrvamsi** [node-influx/node-influx#89]
Code

    var influx = require('influx');
        client = influx({
             host:'localhost',
             port: 8086,
             database:'metrics'
        });

    var points = [
                    [{value:data.num_cores},{tag:'cores',tag:nodes.serverip,tag:hostname}],
                    [{value:data.memory_capacity},{tag:'memory',tag:nodes.serverip,tag:hostname}],
                ]

                client.writePoint('metrics',points,function(err,dat){
                    console.log(dat);
                })

Output
    
    /opt/dockerstack-dashboard/node_modules/influx/index.js:304
    if (!options.database) {
              ^
    TypeError: Cannot read property 'database' of undefined
    at InfluxDB.writeSeries (/opt/dockerstack-dashboard/node_modules/influx/index.js:304:15)
    at InfluxDB.writePoint (/opt/dockerstack-dashboard/node_modules/influx/index.js:326:8)
    at /opt/dockerstack-dashboard/api/controllers/ClusterController.js:166:24
    at /opt/dockerstack-dashboard/node_modules/cadvisor/index.js:23:6
    at ConcatStream.<anonymous> (/opt/dockerstack-dashboard/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:129:20)
    at finishMaybe (/opt/dockerstack-dashboard/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at afterWrite (/opt/dockerstack-dashboard/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:340:3)
    at /opt/dockerstack-dashboard/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:327:9
    at process._tickDomainCallback (node.js:381:11)

**Comment by kgrvamsi** [comment]
Tried with the below and now i get the invalid boolean error

    var points = [
                    [{value:data.num_cores},{metric:'cores',serverip:nodes.serverip,hostname:hostname}],
                    [{value:data.memory_capacity},{metric:'memory',serverip:nodes.serverip,hostname:hostname}],
                ]

                client.writePoint('server_info',points,{database : 'metrics'},function(err,dat){
                    sails.log(dat);
                    sails.log(err)
                })

Output 

     Error: unable to parse 'server_info,database=metrics 0=[object Object],[object Object],1=[object Object],[object Object]': invalid boolean

    at /opt/dockerstack-dashboard/node_modules/influx/index.js:67:23
    at InfluxRequest._parseCallback (/opt/dockerstack-dashboard/node_modules/influx/lib/InfluxRequest.js:118:10)
    at Request._callback (/opt/dockerstack-dashboard/node_modules/influx/lib/InfluxRequest.js:107:10)
    at Request.self.callback (/opt/dockerstack-dashboard/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/opt/dockerstack-dashboard/node_modules/request/request.js:1057:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/opt/dockerstack-dashboard/node_modules/request/request.js:1003:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11) [Error: unable to parse 'server_info,database=metrics 0=[object Object],[object Object],1=[object Object],[object Object]': invalid boolean
]

**Comment by kgrvamsi** [comment]
Got the answer

    client.writePoints('server_info',points,function(err,dat){
                    console.log(dat);
                })

Output 
  
    > show series
    name: server_info
    -----------------
    _key                                                                                    hostname                        metric            serverip
     server_info,hostname=ip-10-20-30-00.ec2.internal,metric=cores,serverip=xx.x.xx.xx      ip-10-20-30-00.ec2.internal     cores   xx.x.xx.xx
    server_info,hostname=ip-10-20-30-00.ec2.internal,metric=memory,serverip=xx.x.xx.xx     ip-10-20-30-00.ec2.internal     memory  xx.x.xx.xx

    > show measurements
    name: measurements
    ------------------
    name
    server_info

    > select * from server_info;
    name: server_info
    tags: hostname=ip-10-20-30-00.ec2.internal, metric=cores, serverip=xx.x.xx.xx
    time                            value
    ----                            -----
    2015-07-29T10:26:22.225Z        1


    name: server_info
    tags: hostname=ip-10-20-30-00.ec2.internal, metric=memory, serverip=xx.x.xx.xx
    time                            value
    ----                            -----
    2015-07-29T10:26:22.225Z        2101297152

**Comment by nichdiekuh** [comment]
You want to use `writePoints` not `writePoint`. ;)

**Comment by kgrvamsi** [comment]
Ya but the error didnt told me to use writePoints instead writePoint when array of Values are given

**Comment by venkates77** [comment]
👍 for `writePoints`...has been a little scramble before figuring out....

**Comment by bencevans** [comment]
I do like the idea of throwing an error if it's an array provided.

@SPARTAN563's work adding TypeScript definitions to the project (https://github.com/node-influx/node-influx/blob/master/index.d.ts) might be beneficial if you wish to use TypeScript. Looks pretty decent (very limited personal experience so far...) and would throw an error before your program starts running!
